### ISSUE TITLE
Upload source tarball to PyPI or issue a GitHub release for the latest version

### ISSUE THREAD

**Issue by ocefpaf** [tjcrone/pycamhd#6]
At the moment there in only a wheels version at PyPI: 

https://pypi.org/project/pycamhd/#files

and the latest release, 0.7.0, is not available/tagged on GitHub:

https://github.com/tjcrone/pycamhd/releases

That makes it hard for third party packagers to package `pycamhd` for other systems that don't use `pip` wheels. Would it be possible to get a source distribution release for the latest version?

**Comment by tjcrone** [comment]
Thanks for taking a look at this @ocefpaf. I am very willing to make this improvement, however I am unfamiliar with the exact steps. Is this something that you can do with a PR? Or if I make you a collaborator? If not, I am willing to follow your instructions and I'll make it happen.

**Comment by ocefpaf** [comment]
It is not something I can do via a PR and, even though I believe I could do as a collaborator you would also need to give me access to the package on PyPI. I guess that it is easier to just,


- tag a release on latest master, which I'm assuming was used to create the PyPI wheel for 0.7.0, by navigating to https://github.com/tjcrone/pycamhd/releases and clicking on the "Draft releases" button.

(For more info see https://help.github.com/articles/creating-releases)

- to publish a source distribution to PyPI you can:

```
python setup.py sdist  # creates the source distribution
python setup.py bdist_wheel  # creates the wheel
twine upload dist/*  # to upload both
```

Note that is probably similar to what you did for the wheel.

Hope that helps.

**Comment by tjcrone** [comment]
Thanks for these reminders. I have tagged two new releases and uploaded an sdist. Please let me know if there is anything else I can help with.

**Comment by ocefpaf** [comment]
Looks good. Thanks!

**Comment by tjcrone** [comment]
Anytime. Are you using pycamhd? How did you hear about it?

**Comment by ocefpaf** [comment]
I'm packaging it on conda-forge:

https://github.com/conda-forge/staged-recipes/pull/6501

to help people install it during the Ocean Hack Week without relying on `pip`.

(The pip package will pull in a numpy wheel and that may break the environment.)

**Comment by tjcrone** [comment]
Thanks for helping with this @ocefpaf! Much appreciated.

**Comment by ocefpaf** [comment]
No problem.
